name: travel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  provider: ^6.1.2
  google_fonts: ^6.3.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48


flutter_native_splash:
  image: assets/icon/splash.png
  color: "#0172B2"
  android_gravity: center
  fullscreen: true

  android_12:
    image: assets/icon/splash.png
    color: "#0172B2"
    
flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
